name: Postgres MCP

on:
  push:
    tags:
      - v*
    paths:
      - pg/**

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git log -1

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.3'
      - run: go version

      - name: Install dependencies
        run: |
          cd pg
          go mod download

      - name: Build and publish package
        run: |
          cd pg
          GOOS=windows GOARCH=amd64 go build -o pg-mcp.exe cmd/mcp/main.go
          go build -o pg-mcp cmd/mcp/main.go

      - name: Packaging applications
        run: |
          cd pg
          tar -czf windows-pg-mcp.tar.gz pg-mcp.exe README.md
          tar -czf linux-pg-mcp.tar.gz pg-mcp README.md
          sha256sum *.tar.gz > checksums-pg-mcp.txt

      - name: Upload package
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd pg
          gh release create ${{ github.ref_name }} \
            windows-pg-mcp.tar.gz \
            linux-pg-mcp.tar.gz \
            checksums-pg-mcp.txt \
            --title "Release ${{ github.ref_name }}" \
            --generate-notes